version: "3.8"

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  app_setup:
    build: .
    volumes:
      - .:/code
    env_file:
      - .env
    command: >
      bash -c "
      pipenv install &&
      if [ '${APP_NAME}' ] && [ ! -d 'src/${APP_NAME}' ]; then
        echo 'Creating new app ${APP_NAME}...' &&
        bash /code/generate_app_files.sh ${APP_NAME} \"${MODELS_DATA}\";
      else
        if [ '${APP_NAME}' ]; then
          echo 'App ${APP_NAME} already exists, skipping creation.';
        fi
      fi
      "

  web:
    build: .
    command: >
      bash -c "
      pipenv install &&
      pipenv run python manage.py makemigrations &&
      pipenv run python manage.py migrate &&
      pipenv run python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - app_setup

volumes:
  postgres_data:
